# Generated by Django 6.0 on 2025-12-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
