# Generated by Django 5.1.6 on 2025-12-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_id_companyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
